### ISSUE TITLE
Apply Now button is missing at the bottom of the text on mobile

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#112]
The one in the header is behind the hamburger, so that is OK.
The Hero text one is present in both.

But the one at the bottom is missing on mobile where it could easily be present.

**Comment by SPTechnology** [comment]
I have fixed this issue now

**Comment by bobsummerwill** [comment]
Fixed in https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/123
