### ISSUE TITLE
We need to freeze the text "soon" and get it all translated.   Maybe Bitmain do that?

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#116]

**Comment by andrewgdick** [comment]
Once our team is happy with the website we will lock down the Copy and send it to Bitmain

**Comment by bobsummerwill** [comment]
OK - we are done.

No need to send them the copy.   They have access to the Github repo and can make the changes to the Chinese MD files themselves.  That is what was communicated to them in the meeting on Wednesday, and since in the Telegram group
