### ISSUE TITLE
Add some highlighted text for the dates in Round 1 section

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#129]
As per Bitmain suggestion we should do some green text or other highlighting for the dates in Round 1 section.

Having the timeline clearly communicated on the webpage is something several people have mentioned.   We just have not done it yet.

**Comment by bobsummerwill** [comment]
This would mean introducing some element in the MD for highlighting.

I tried doing the double-stars for bold which is common in Markdown but that made no difference.

Maybe that is a CSS issue?   Could you try to make it so that bold markup in the MD files comes out as Parrot Green but without the underscores?  Thanks!

**Comment by gd8097019** [comment]
Hi I added custom CSS rule for that and tested in `how-to-apply.en.md` file. Check my last PR

<img width="772" alt="Screen Shot 2023-01-25 at 12 00 50" src="https://user-images.githubusercontent.com/102132498/214521766-0fb85a4d-9112-46ab-bafc-ec68f24782f7.png">
<img width="824" alt="Screen Shot 2023-01-25 at 12 00 38" src="https://user-images.githubusercontent.com/102132498/214521796-f7e44eec-140f-4527-9335-e7f6c7f80781.png">

**Comment by bobsummerwill** [comment]
Thanks!   Seeing it like that, it actually blends in with the titles, doesn't it?
Please could you actually just try it with a normal **bold**?  Thanks!

**Comment by bobsummerwill** [comment]
Grabbed out and modified your changes here, so using bold not green.
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/166
