### ISSUE TITLE
Footer improvements

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#132]
ETC Grants DAO social links are listed in the Resources section, but I think they should be in the footer itself too.

Also the footer has ETC Cooperative and then PARTNERS on the right hand side.   That is wrong and must be design work from the ETC Cooperative website.   It is not correct here.

We are all partners together and all of the columns should look the same.  No PARTNERS label in the footer.

**Comment by andrewgdick** [comment]
I'm not sure this should be assigned to me.

**Comment by bobsummerwill** [comment]
Sent back to me.

**Comment by andrewgdick** [comment]
Merged into #154
