### ISSUE TITLE
What images do we want on the website?

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#141]
We need to make a plan, share that plan with Bitmain and then get those images done and into the site.

**Comment by andrewgdick** [comment]
Stock photos? We don't have any professional images as far as I know.

**Comment by bobsummerwill** [comment]
The TODO here is working out what visuals we want through the text to break it up a bit.

These could be stock images or graphics we have made up relating to the grants process details.

**Comment by bobsummerwill** [comment]
OK - we won't do more.
The two tables, watermark and logo are good enough.
