### ISSUE TITLE
Text broken when improving the links

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#149]
See grantsProcess.phases.step3.mayBeDeclined.body.bullets.b1 and other bullets showing up.

If all the MDs are done then this will be fixed in the process, but just wanted to track it.

**Comment by gd8097019** [comment]
I also saw this issue when I convert text to .md files. After the last PR you can easily edit from `etc-grants-process.en.md` and `etc-grants-process.cn.md` file

**Comment by bobsummerwill** [comment]
Thanks
