### ISSUE TITLE
Create a sections.json file

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#153]
So we are not hard-coding them.

Bob said:

"Sure - that would be useful.
There are three separate navigation controls.  Anything you could do to simplify that would be helpful."

**Comment by bobsummerwill** [comment]
If you have a look at the en.json and cn.json now you will see that they hardly have any text left in them.
I have stripped out all of the translations which we are not using anymore, because the text has gone into the MD files.

You will see that nearly all of it is for the nav headings for the scrolling sections.

So maybe that fits in with what you were considering for this issue - making that data-driven within a single file which includes the section structure and the translations together?

Something like this?

"sections" {
    "overview": {
        "en": "ETC Grants DAO",
        "zh": "ETC Grants DAO",

        "subsections": {
            "etc-grants-dao": {
                "en": "ETC Grants DAO",
                "zh": "ETC Grants DAO"
            },
            "etc-grants-program": {
                "en": "ETC Grants Program",
                "zh": "ETC Grants DAO"
            },
    },
    "howToApply" : {
        "en": "How to Apply",
        "zh": "意见反馈"
    }

**Comment by bobsummerwill** [comment]
Or we could keep them apart?

We should probably switch from "cn" to "zh" everywhere too, btw.

**Comment by gd8097019** [comment]
`vue-i18n` module load locale files from this code block: 

```
function loadLocaleMessages() {
  const locales = require.context('./locales', true, /[A-Za-z0-9-_,\s]+\.json$/i)
  const messages = {}
  locales.keys().forEach(key => {
    const matched = key.match(/([A-Za-z0-9-_]+)\./i)
    if (matched && matched.length > 1) {
      const locale = matched[1]
      messages[locale] = locales(key).default
    }
  })
  return messages
}
```

I think I can import section.js file properties and merge with final local files which means you can use in code as `$t('sections.overview')` or `$t('sections.overview.etc-grants-program')` 

I will try like that.

**Comment by bobsummerwill** [comment]
Thanks!
