### ISSUE TITLE
URGENT - Switch the footer to be the Grants footer

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#16]

**Comment by andrewgdick** [comment]
The Footer should be 4 columns

Bitmain
Bitmain Logo https://www.bitmain.com/
Bitmain Social Media
https://twitter.com/BITMAINtech
https://t.me/bitmain

Antpool
Antpool Logo - https://www.antpool.com/home
Antpool Social Media
https://t.me/AntPoolOffical
https://twitter.com/AntPoolofficial

Ethereum Classic (ETC)
ETC Logo - https://ethereumclassic.org/
ETC Social Media
https://discord.com/invite/bMGuZsA
https://twitter.com/eth_classic

ETC Cooperative
ETC Cooperative Logo - https://etccooperative.org/
ETC Cooperative Social Media
https://discord.com/invite/5wDyd6u6pU
https://twitter.com/ETCCooperative

**Comment by SPTechnology** [comment]
To confirm, is there a pre-set design for a 'Grants' footer somewhere, or should we just create it with the above links and columns in mind?

**Comment by andrewgdick** [comment]
There is no Grants footer. Please create it with the above links, logos, social media and columns, thanks.

**Comment by SPTechnology** [comment]
Understood. To Bela for design.

**Comment by bobsummerwill** [comment]
Are you going to be able to look at this over the weekend, @SPTechnology?  Thanks!

**Comment by bobsummerwill** [comment]
Or still waiting on Bela for design?

**Comment by bobsummerwill** [comment]
Are you working on this today, Scott?

**Comment by SPTechnology** [comment]
Bela's working on it yes. Still waiting on the design (she said she's completing it today and sending over)

**Comment by bobsummerwill** [comment]
We really need this today, please.  Thanks!

**Comment by SPTechnology** [comment]
Yes, done with this

**Comment by bobsummerwill** [comment]
Fixed in https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/123
