### ISSUE TITLE
URGENT - Footer Issues on Mobile

### ISSUE THREAD

**Issue by andrewgdick** [ETCGrantsDAO/etc-grants-dao-website#162]
On mobile:
1. Footer has spacing issues for Brands
2. "Apply" button missing

**Comment by bobsummerwill** [comment]
I will fix the Apply button.

**Comment by bobsummerwill** [comment]
Fixed Apply Now in https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/165.

Footer spacing issues remain.

**Comment by bobsummerwill** [comment]
Closing this to make a new clearer one.
