### ISSUE TITLE
Can we pull the main text, mobile and desktop navs out into their own component files?

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#17]
Rather than having everything in a single Vue file?

**Comment by SPTechnology** [comment]
Yes, agreed. Check pull request I'm making and let me know if this is the intended method or if we should change it. If that works, we can continue to use that method of individual component files for the various Paragraphs, Navs, etc.

**Comment by bobsummerwill** [comment]
Done.
