### ISSUE TITLE
URGENT - Font sizing and proportions do not look good.  Bullet-points need to be real ones.

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#22]
The site looks a lot better on my iPhone than on my Mac (Brave).
It might well be using different fonts (maybe even built-in ones?).

The main text size is good on mobile but is too large and chunky looking on Desktop.
The bold main titles are too much, I think.

Also, on both mobile and desktop there is too much whitespace between the paragraphs.

Here was my draft website.  It is a lot more readable:

https://fanciful-hotteok-d28b8e.netlify.app/en/

**Comment by SPTechnology** [comment]
Understood - looks like the desktop view matches the Figma design pretty perfectly on the desktop version, but I agree it's a bit 'chunky'. Will provide this feedback to Bela to get the design updated so we don't go off the rails vs the Figma design. 

For now, if you have specific font size values you'd prefer we can just do that, but usually, I consult with the designer(s) before making a change like that. Will ask her opinion and hopefully get it first thing this AM

**Comment by SPTechnology** [comment]
Bela's made the Figma changes. Will implement

**Comment by bobsummerwill** [comment]
Great - thanks.

I am no expert but maybe 10pt for the main text?
And the padding is too much as well.

Let me also try using some real bullet-points versus - and br elements.

I think that looked pretty bad when I tried.

**Comment by bobsummerwill** [comment]
Are you going to be able to look at this over the weekend, @SPTechnology?  Thanks!

**Comment by SPTechnology** [comment]
This one is fixed. Our current implementation matches the exacts fonts being used in figma. Also in latest push I have also converted to paragraph to list

**Comment by bobsummerwill** [comment]
Thanks!

The main headers are running into the text above them.   I did have horizontal breaks in the MainHeading component which I had inserted as a temporary improvement on this but have since removed it because it was a hack on my behalf.

Please could you update the MainHeading and SubHeading components appropriately to correct this misspacing?

With regard to spacing around the sub-headings and paragraphs, it might match the Figma now, but I don't think it looks good.  Please can you pull those a little tighter?   So less padding around of of the elements (MainHeader, SubHeader, Paragraph)?   Or you can just let know where I can tweak that myself.

On the bulletpoints, so I see you are using "ul" and "li" elements now, but still using explicit "-" text.   What I meant was using those elements and tweaking the CSS so that they were actually displaying bullets and indented a little.
