### ISSUE TITLE
Switch Apply Now button under Hero to be the same as the one in the header

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#234]
Please can you switch the Apply Now button under the Hero control to be exactly the same as the one in the header?

I tried cut-and-pasting it, but it needs some kind of tweak.

So not popping, white border and horizontally centered text.  Thanks!

**Comment by gd8097019** [comment]
Check my PR: https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/243

**Comment by bobsummerwill** [comment]
Fixed
