### ISSUE TITLE
Grants categories table full-width on Desktop please

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#238]
The Grants Categories table is no longer full width on Desktop, but it needs to be, because there is a lot of content in there.
I imagine it got shrunk in the same change which made the flow diagram narrower on desktop.

If it feasible to make that Grant Categories full width again?   Would need to have two styles/tags I guess?  Thanks!

**Comment by gd8097019** [comment]
Please check my PR  https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/243
<img width="1173" alt="Screen Shot 2023-01-30 at 15 29 15" src="https://user-images.githubusercontent.com/102132498/215477192-b94d5509-2816-4f44-b15d-97b8cf28a196.png">

**Comment by bobsummerwill** [comment]
Fixed - thanks!
