### ISSUE TITLE
Please can you try to make a background watermark image?

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#250]
Gabriel is having difficulties.
It needs to be at least 500 x 1000, and should look like the watermark in our previous retrospectives, but with a transparent background.

I will drop you the files in Discord.  Thanks!

**Comment by andrewgdick** [comment]
i have attached an image here for the background
![bg-image](https://user-images.githubusercontent.com/974129/215753396-3cc96e94-92ad-4546-be16-4324b95e11ce.png)

**Comment by bobsummerwill** [comment]
Thanks, but please can you do a version with the image 1/3 off-screen, just like that original white version in the retrospective?  Thanks!

**Comment by andrewgdick** [comment]
![watermark-egd](https://user-images.githubusercontent.com/974129/215821303-14b07144-cf93-49f6-a878-0c2582d5b383.png)

How is this?

**Comment by bobsummerwill** [comment]
Looks good.  Want to stick it in and see how it goes?  Thanks!
