### ISSUE TITLE
Mobile footer - ETC Grants DAO stretched and missing Telegram link - Gabriel cannot reproduce

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#255]
The changes in https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/251/files made the mobile footer a lot better, but the section at the top, with "ETC Grants DAO" is slightly misformatted compared to the bottom section with the sponsors.

The logo is stretched too wide horizontally, and the Telegram icon is missing.  I can see it is still there in the Vue file so this much be a formatting issue.

The twitter and telegram icons should be aligned to those icons in the lower section, and the logo should not be stretched.

**Comment by bobsummerwill** [comment]
@gd8097019 cannot reproduce this issue, which is happening on Bob's iPhone 13.

**Comment by andrewgdick** [comment]
And happening on Andrew's iPhone XR ![image](https://user-images.githubusercontent.com/974129/216062076-ef1f4f04-5303-4907-bc5a-f76ba4d6321e.png)

**Comment by gd8097019** [comment]
I checked in my Android Xiamoi phone there is no problem. I did a small css updates. Can you try this PR: https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/275
