### ISSUE TITLE
"Hero" Apply Now button has disappeared on mobile.

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#256]
"Hero" Apply Now button has disappeared on mobile, and is word-wrapping for me on Desktop (where the one of the header nav is not).   This must have happened while changing it to be like the one on the header

**Comment by bobsummerwill** [comment]
This regression was introduced in https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/243.

**Comment by bobsummerwill** [comment]
So I reverted the change which made the Apply Now button disappear on mobile:
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/257

Please could you redo that change, but testing on mobile as well, please, Gabriel?  Thanks!

**Comment by gd8097019** [comment]
Hi Bob, I fixed and checked with mobile. See my PR. 

I could not modify `tailwind.config.js` but you can modify `heroButtonMobileWidth:` , `heroButtonDesktopWidth` to determine width of button

**Comment by bobsummerwill** [comment]
Fixed with https://github.com/ETCGrantsDAO/etc-grants-dao-website/pulls?q=is%3Apr+is%3Aclosed
