### ISSUE TITLE
Header translations got broken

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#259]
The changes to replace the hard-coded header nav titles with a for-loop broke the translations.

Here is where the break was introduced:

https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/251

Broken changes reverted at:

https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/258

Please could you rework this code NOT NOW but later in the week, post-launch?  Thanks!

**Comment by gd8097019** [comment]
Hi Bob, after your revert it looks working. Can you describe more about to do for this issue? Which feature reverted? I can rework again to that.

**Comment by bobsummerwill** [comment]
Resolved now.
