### ISSUE TITLE
Need to redo the Chinese grants categories table

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#262]
I added an updated grants category table from Adolph:
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/261

We needed the correct text more, but the style is not the same (white background now).

Please can you re-generate that graphic in the same style as the others and merge it?  Thanks!

**Comment by andrewgdick** [comment]
Updated
