### ISSUE TITLE
Remove See More on project views

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#293]
For both English and Chinese project views, please can we remove the See More button and just list all proposals?

... even though it does make it very long.  The reviewer is reviewing and adding that button just slows them down.

**Comment by bobsummerwill** [comment]
Unresolved as of June 12th.

**Comment by ahmet-shamiev** [comment]
Just checked. No See More button for both En and Cn lists in Reviewer's dashboard.

**Comment by bobsummerwill** [comment]
Thanks.  Please can you also change:

https://etcgrants.softr.app/projects-list-en
https://etcgrants.softr.app/projects-list-zh

**Comment by ahmet-shamiev** [comment]
Resolved. But please take into account that Softr may display only per 100 items in each of these list blocks.

**Comment by bobsummerwill** [comment]
Great - thanks!

If there are over 100, would the "See More" be displayed again?  If so, that is fine.
