### ISSUE TITLE
"Reviewed" in top navigation bar is redundant now

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#298]
As we now have filters at the top of the Reviewer dashboard, the "Reviewed" in the top nav bar does not make sense anymore.
There is no anchor for it to point to.
Please can we just remove it?  Thanks!

**Comment by bobsummerwill** [comment]
Unresolved as of June 12th.

**Comment by ahmet-shamiev** [comment]
Done it.

**Comment by bobsummerwill** [comment]
Confirmed fixed.
