### ISSUE TITLE
Remove seemingly unused columns in the airtable

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#301]
Browsing through the airtable for Giveth, it appears that we have some unused fields which we should delete.
We went through a couple of rounds of refinement on these, so the unused ones will be from earlier, before all the data was actually populated.

From what I can see the following are all empty (please can you double-check) and not used in any views.   Please can you remove them?

Team Member Names - EN
Team Member Names - ZH
Team Member Country of Residences - EN
Team Member Country of Residences - ZH
Project Category - EN (Grant Category - EN is used instead)
Project Category - ZH (Grant Category - ZH is used instead)
Application Type - EN
Application Type - ZH
Corporate Location - EN
Corporate Location - ZH
Description of Problem or Opportunity - EN
Description of Problem or Opportunity - ZH
Proposed Solution - EN
Proposed Solution - ZH
ETC Ecosystem Benefit - EN
ETC Ecosystem Benefit - ZH
Address Obstacles - EN
Address Obstacles - ZH
ETC Cooperative/Ecosystem Support - EN
ETC Cooperative/Ecosystem Support - ZH
Expected Project Launch Date - EN
Expected Project Launch Date - ZH
Qualitative Metrics - EN
Qualitative Metrics - ZH
Goals and KPIs - EN
Goals and KPIs - ZH

Seemingly missing?

Funding from Other Sources - ZH (Funding from Other Sources - EN exists and is being used.   Is this just missing in the Chinese views?)
Project Timeline & Milestones - ZH (Project Timeline & Milestones - EN exists and is being used.   Is this just missing in the Chinese views?)

**Comment by ahmet-shamiev** [comment]
Listed unused fields are deleted. As for mentioned last two fields in Chinese (Funding from Other Sources - ZH and Project Timeline & Milestones - ZH), these are being filled primarily in English version only.

**Comment by bobsummerwill** [comment]
Thanks for the deletions!   I think there is one more to remove - Link to Chinese version.

>> As for mentioned last two fields in Chinese (Funding from Other Sources - ZH and Project Timeline & Milestones - ZH)
>> these are being filled primarily in English version only.

So it looks like you have added these columns now?   Are they being used in the Chinese views?

I see one other confusing column - Explain ETC fit (f) - what is this?  Is it unused and can be deleted?

There are also a handful of fields which I think would be the same whether an application is first in English or Chinese.  Would it be possible to collapse there into a single field for both languages, please?   And then these ones would be removed from the translation views, because they would not need translating:

- Twitter URL
- Github repository
- Contact name
- Contact email
- Total request

**Comment by ahmet-shamiev** [comment]
Hi Bob, Yes, both of these fields are available in project details page of Chinese projects. (Funding from Other Sources - ZH and Project Timeline & Milestones - ZH).

**Comment by ahmet-shamiev** [comment]
Explain ETC fit (f) - doesn't carry any sensible information and not linked to front pages. So I also deleted it.

**Comment by ahmet-shamiev** [comment]
The issue of collapsing below fields is that when an applicant fills the form he sees the field depending on language version chosen in the first step.  So, if we stick to only one field, its name won't change depending on language type. For all, both en and cn applicants the name of the field will stay the same. However, we may add translation into brackets or leave only en version, since most probably every applicant can understand these basic meanings. 


Twitter URL
Github repository
Contact name
Contact email
Total request

**Comment by bobsummerwill** [comment]
OK - so let's forget about that collapsing, then.

Does the mapping of email addresses to user accounts take account of the fact that there are both English and Chinese fields for email address?   It is looking for the English field for English proposals and to the Chinese field for Chinese proposals?

Closing this issue because I don't think there is more work to do here,
