### ISSUE TITLE
project-details-translation-en and project-details-translation-zh views missing email

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#302]
We intentionally hide the email field from the public in the project details views, but it needs to be present for review and translator views.

Looks like it is just the translation project view which is missing it.   Please can you add?  Thanks!

**Comment by ahmet-shamiev** [comment]
Ok, this one is completed.

**Comment by bobsummerwill** [comment]
Fixed

**Comment by bobsummerwill** [comment]
Oops - no - a bug here in the translator view in at least project-details-translation-en but maybe also in project-details-translation-en.

The new email field is in a different tiny font.

**Comment by bobsummerwill** [comment]
Still a todo here ^

**Comment by ahmet-shamiev** [comment]
Yes, so that. Fixed.

**Comment by bobsummerwill** [comment]
Thanks
