### ISSUE TITLE
Translated English proposals are NOT showing up in the Chinese projects-list view

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#304]
Both Giveth and POW Summit have been translated to Chinese now, to test the workflow, but neither are showing up in the Chinese projects list view.

**Comment by ahmet-shamiev** [comment]
Hi @bobsummerwill , I think this is old task, all translated projects are visible in Chinese list of projects. Please check it. 
<img width="1193" alt="image" src="https://github.com/ETCGrantsDAO/etc-grants-dao-website/assets/61404173/64f14726-b3cd-4f06-a62a-09e68263214a">
 
<img width="1209" alt="image" src="https://github.com/ETCGrantsDAO/etc-grants-dao-website/assets/61404173/99fa7de8-2e80-4959-80ae-08f77896264f">

**Comment by bobsummerwill** [comment]
Verified fixed, thanks.
