### ISSUE TITLE
Please can you introduce the same folds into the translator dashboard?

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#305]
The translator dashboard is seemingly the last view which still has the "cards".
Please you switch it to have the same fields showing in the folds as the main project lists?
And the same Read More pattern as for the reviewer dashboard.  Thanks!

**Comment by ahmet-shamiev** [comment]
Hi Bob, I shifter the same UI to the Translator's dashboard, please check.

**Comment by bobsummerwill** [comment]
Thanks!
