### ISSUE TITLE
Add support for translation of the Review field

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#306]
Please can you a Chinese version of the Review field, and add that into the Chinese translation form?

project-details-translation-en
project-details-translation-cn

I think we are fine for now to have the Translator and Reviewer dashboards remaining English language and displaying reviews in both languages, so not having a corresponding Chinese workflow:

translator-dashboard
reviewer-dashboard

... but the Review Comments field for the Chinese applications in both of these dashboard should start to show the Chinese review field, not the English field.

And applicant-dashboard is English only and that is OK.

project-details-review and project-details-cv-reviewer should show the Review or Chinese Review at the bottom of the existing fields along with all the other fields.

Small refactor for consistency:

project-details-review should be renamed as project-details-review-en
project-details-cv-reviewer should be renamed as project-details-review-cn

**Comment by ahmet-shamiev** [comment]
If we create separate Chinese Review field, you should migrate some existing reviews for Chinese projects from Review (EN) field to Review(CN).

**Comment by ahmet-shamiev** [comment]
"Please can you a Chinese version of the Review field, and add that into the Chinese translation form?"

Above task is completed. Review filed is available in both languages translation forms.

**Comment by ahmet-shamiev** [comment]
"Small refactor for consistency:

project-details-review should be renamed as project-details-review-en
project-details-cv-reviewer should be renamed as project-details-review-cn"

Completed.

**Comment by bobsummerwill** [comment]
Looks like everything is done here - thanks!
I will make new issues for anything else I spot.
