### ISSUE TITLE
Missing Chinese translations in workflow

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#307]
Just testing the new translation workflow for the Review field, I went here (Shitcoin Swap):

https://etcgrants.softr.app/project-details-translation-en?recordId=recvGhlrG7vG91JES

And the airtable form which it shows me has Chinese headings for everything EXCEPT:

Form Language
Project Name
Review (CN)

1. I would expect Form Language to have both English and Chinese text (there is only one field in the DB), but better yet would be NOT to show that field, because we do not want it to be changed as part of the translation workflow.
2. I would expect Project Name and Review fields to have ONLY Chinese text.
3. We should not be showing the English Project Name anyway.

You should already have translations for the first two, but I will ask our reviewer for translations for all three of these.

**Comment by bobsummerwill** [comment]
Some issues the other way around, going from Chinese to translate to English:

https://etcgrants.softr.app/project-details-translations-cn?recordId=reczX7MHWj0eWa5LO (BlockModel)

1. We should not need to show the Form Language.  We don't want that changed.
2. The airtable form shows 项目名称 heading (which is the Chinese project name).  We should not need to show that.
3. "Please include a breakdown of your budget - EN" should not have the -EN suffix
4. Review (EN) should say "Review Comments"

**Comment by bobsummerwill** [comment]
Translations:

Project Name: 项目名称
Review Comments: 浏览评价
Form Language: 表格语言

**Comment by ahmet-shamiev** [comment]
Updates completed to the following fields: 

Form Language
Project Name
Review (CN)

**Comment by ahmet-shamiev** [comment]
Updates for the following points has also been delivered: 

- We should not need to show the Form Language. We don't want that changed.
- The airtable form shows 项目名称 heading (which is the Chinese project name). We should not need to show that.
- "Please include a breakdown of your budget - EN" should not have the -EN suffix
- Review (EN) should say "Review Comments"

**Comment by bobsummerwill** [comment]
OK - I think everything is resolved here.
I see some other minor problems, but will make new issues for them.
