### ISSUE TITLE
Reviews are not showing in translator-dashboard

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#308]
The review text is all showing as blank in the translator-dashboard.

I assume that happened as a result of the change of the column name in airtable?
Something needs updating there to match?

This might be happening on other views too.  Please can you verify?  Thanks!

**Comment by ahmet-shamiev** [comment]
Hi Bob, Yes, I updated this, now reviews for English applications are showed for the Reviewer and Translator. However, since there wasn't Review column for projects in Chinese, reviews for them are stored in Review columns for English projects. Do you want me to move them, move comments for Chinese projects from Review in En column to Review in CN?

**Comment by bobsummerwill** [comment]
The strings are fine as they are (so only showing for the English proposals).
The Chinese review fields would be populated:
- By reviewing a Chinese proposal
- Or by translating an English proposal

Please can you ensure that the modal dialog in https://etcgrants.softr.app/project-details-review-en lets you update the English Review field and common Funding fields, and that https://etcgrants.softr.app/project-details-review-cn lets you update the Chinese review field and the common Funding field?

At the moment, the modal dialogs from those views ONLY show that Funding field.   Presumably that is again because of the renaming of the columns?

So no need for changes to the actual data - just to ensure these flows are working as expected.  Thanks!

**Comment by bobsummerwill** [comment]
Ok, I think this is all covered except that the modal dialogs are missing the review fields.

**Comment by ahmet-shamiev** [comment]
OK, I've updated the mapping. Review fileds are shown in both modals, for en and cn review modals.
