### ISSUE TITLE
URGENT (2/4) - Abstract all of the formatting out of HTML into CSS files

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#31]
The HomeVue.js raw HTML is littered with specific CSS styles on a per element basis.
This is completely unmaintainable.

ie.

            <div class="text-headingsColor">
              <p
                class="font-notoSans text-headingsColor text-twentyFour leading-thirtySix md:text-thirtyTwo md:leading-rightHeadingsDt rightSecHeading"
              >
                {{ $t("about.ethereumClassicIn2023.heading") }}
              </p>
            </div>
            <div class="pt-12"></div>
            <div>
              <p
                class="font-roboto text-textColor text-base md:text-heroTextMobile md:leading-thirtyThree righttSecText"
              >
                {{ $t("about.ethereumClassicIn2023.body.p1") }}
              </p>
            </div>
            <div class="pt-12"></div>
            <div>
              <p
                class="font-roboto text-textColor text-base md:text-heroTextMobile md:leading-thirtyThree righttSecText pb-8"
              >
                {{ $t("about.ethereumClassicIn2023.body.p2") }}
              </p>
            </div>

Should be:

            <h2>
                {{ $t("about.ethereumClassicIn2023.heading") }}
            </h2>
            <p>
                {{ $t("about.ethereumClassicIn2023.body.p1") }}
            </p>

Maybe with class div around the whole thing, but the redundancy (and especially the number of classes) makes changes in style  very laborious.

**Comment by SPTechnology** [comment]
Thought: 

We are using Tailwind to minimize the CSS; should we not make 'true' use of VUE's components and build the CSS into reusable components that can be fed the text in JSON? 

If we do this, the components can be reused anywhere in the project without the need for the standard HTML tags ( <h1>, <p>, etc... ) Take a look at the ones I'm pushing now and LMK if you think this is a better method.

**Comment by bobsummerwill** [comment]
Components are good, yes.
I liked what you did with Paragraph, Heading, etc.

**Comment by bobsummerwill** [comment]
Is it just the case that you or Mohammad need to work through the rest of the Vue files now, and switch to using the new Common components for everything?

So switch for "p" to "Paragraph", etc?

**Comment by bobsummerwill** [comment]
So this is certainly better, but the components for the sub-sections are still pretty cut-and-paste ugly.

**Comment by bobsummerwill** [comment]
@SPTechnology Gabriel is starting work with us tomorrow.

He is a Vue.js expert and I'm reassigning these structural issues to him.

**Comment by bobsummerwill** [comment]
Superceded by https://github.com/ETCGrantsDAO/etc-grants-dao-website/issues/96.
