### ISSUE TITLE
Translation details page - Please replace small "circle" button with large button at the bottom.

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#311]
Extra 1 - The "circle" button on the top right of the screen here is TINY and not obvious:

https://etcgrants.softr.app/project-details-translation-en?recordId=recNgFDKdD1K7XSZ1

I am asking whether you can please replace that with a normal sized button at the bottom on that view, so you would have:

"Back to Dashboard" "Translate" and "Update Translation" and not have the pencil icon - just the three large buttons.

**Comment by ahmet-shamiev** [comment]
Hi Bob, 

Please watch my short video regarding buttons for editing and pop-up window/text field issues.

https://www.loom.com/share/193873e82dc849afad821cbb08a4195c?sid=0387637c-a458-4165-a71b-3e88e65edf53

**Comment by bobsummerwill** [comment]
OK - thanks - let's just leave everything as-is then.
