### ISSUE TITLE
Review field blank for English only

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#312]
The Review Field entry in the project review view ONLY for English is blank.  Again, this will be due to the renaming.

ie. https://etcgrants.softr.app/project-details-review-en?recordId=recHBC1GES5DpKSPF

**Comment by ahmet-shamiev** [comment]
Hi Bob, this is fixed now.

**Comment by bobsummerwill** [comment]
Thanks!
