### ISSUE TITLE
Switch to Chinese headings and Chinese buttons throughout

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#313]
There are several places on the Chinese views where we still have English headings.

I will try to enumerate them here, but there might be more.  We can review again when these are addressed:

1. https://etcgrants.softr.app/projects-list-zh - seems good.
2. https://etcgrants.softr.app/project-details-zh - seems good
3. https://etcgrants.softr.app/translator-dashboard (Chinese section) - please use Chinese titles within the folds for the Chinese projects and Chinese text for Read More.
4. https://etcgrants.softr.app/reviewer-dashboard (Chinese section) - please use Chinese titles within the folds for the Chinese projects and Chinese text for Read More.
5. https://etcgrants.softr.app/project-details-translations-cn.  Back to dashboard and translate buttons to Chinese.
6 https://etcgrants.softr.app/project-details-review-cn - seems good.

7. For the language-neutral translator-dashboard and reviewer-dashboard, please use both English and Chinese text for the main title, and then English for English section and Chinese for the Chinese section.   I understand that we are probably stuck with English text for the actual status fields (because we don't have duplicated fields in the database)

TRANSLATOR's DASHBOARD
翻译者信息中心

REVIEWER DASHBOARD
审核员信息中心

PROJECTS IN ENGLISH
英文项目

PROJECTS IN CHINESE
中文项目

TRANSLATION STATUS
翻译状态 

NEEDS TRANSLATION
需要翻译

TRANSLATED
已翻译

REVIEW STATUS
审核状态

NOT REVIEWED
未审核 

REVIEWED
已审核

FUNDING STATUS
资金状态 

FUNDED
已获资助

UNFUNDED
未获资助

BACK TO DASHBOARD
返回返回信息中心

TRANSLATE
翻译

**Comment by ahmet-shamiev** [comment]
Hi Bob, in the process of applying translations. However, can I ask you to share translations for the button "Read More" and text for the Search field - "Type here to search"

**Comment by bobsummerwill** [comment]
Hey - there is a Read More already on one of the other views.
I will ask Angelah for "Type here to search".

**Comment by bobsummerwill** [comment]
Read more: 阅读更多

Type here to search：点击此处搜索

**Comment by bobsummerwill** [comment]
On the Chinese versions of Funded / Unfunded, let's forget that then.  Too much to change the fields.

**Comment by ahmet-shamiev** [comment]
ok, in this case the task seem to be completed. Please check.

**Comment by bobsummerwill** [comment]
Thanks!
