### ISSUE TITLE
Remove buttons to go back to dashboards

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#314]
Many best to just remove those buttons entirely.
The dashboard is still there in another tab.

**Comment by ahmet-shamiev** [comment]
Hi Bob, 

Do you mean removing these "Back to Dashboard" buttons at the bottom of page? 
<img width="748" alt="image" src="https://github.com/ETCGrantsDAO/etc-grants-dao-website/assets/61404173/2c8cdfc1-3a96-4fe8-bc26-ab1b28802ea9">

**Comment by bobsummerwill** [comment]
Yes, that is what I mean.  Thanks!

**Comment by bobsummerwill** [comment]
So the following views still have a "Back to Dashboard":

- project-details-translation-en
- project-details-translation-cn
- project-details-review-en
- project-details-review-cn
- project-details-en
- project-details-zh

When these details pages are opened from the dashboard they always open another tab and you still have the original dashboard open in the original tab.   Clicking on "Back to Dashboard" just gives you two instances of the dashboard and then clicking on another project gives you another again.

I think it is simpler to just delete this button.  Thanks!

**Comment by ahmet-shamiev** [comment]
While on projects list page, we may also disable opening of the a new tab, just forward user on the same page? This will eliminate possibility of having two same pages if the user clicks "Back to dashboard"

**Comment by ahmet-shamiev** [comment]
Ok, in the following dashboards when the user clicks "Read more", the page will be re-directed in the same tab:

- Reviewer dashboard
- Translator's dashbaord
- Your Dashboard (User's)
- Projects lists (both in EN and CN)

So, the issue of having two duplicate tabs has been resolved.

**Comment by bobsummerwill** [comment]
Verified.  Thanks!
