### ISSUE TITLE
EN or CN toggle for project list brings up modal dialog

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#315]
Clicking on the language button at the top of these:

https://etcgrants.softr.app/projects-list-en
https://etcgrants.softr.app/projects-list-zh

Does not take you to the other view.  It pops up a modal dialog with the other view as a sub-panel.

**Comment by ahmet-shamiev** [comment]
I actually thought it's what your requested. But I've already updated flow, so the after the click new window opens with corresponding language.

**Comment by bobsummerwill** [comment]
Thanks.
