### ISSUE TITLE
Making ONLY funding status public

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#317]
https://etcgrants.softr.app/projects-list-en
- Duplicate the main body of the view, so we have all the Funded projects listed first, and then another duplicated chunk with the Unfunded ones
- We would retain the filter by category at the top, to be applied across both sections.  If that needs duplicating too that is OK.
- Switch under the fold heading to Total Request, Project Description and Review Comments (same as reviewer-dashboard)

https://etcgrants.softr.app/projects-list-zh
- Same as above, but with Chinese headings

https://etcgrants.softr.app/projects-details-en
- Add Review Comments field
- Add Funding field

https://etcgrants.softr.app/project-details-zh
- Same as above, but with Chinese headings

**Comment by ahmet-shamiev** [comment]
Hi Bob, 

Ok, I should not start updating anything from the above list, right? Or don't do just the review and funding statuses public? 

_"https://etcgrants.softr.app/projects-list-en

- Duplicate the main body of the view, so we have all the Funded projects listed first, and then another duplicated chunk with the Unfunded ones
- We would retain the filter by category at the top, to be applied across both sections. If that needs duplicating too that is OK.
- Switch under the fold heading to Total Request, Project Description and Review Comments (same as reviewer-dashboard)"_


Here, should I create new blocks for funded and unfunded or merge it with existing just by adding new filter (funding status)?

**Comment by bobsummerwill** [comment]
Please don't anything yet.

New blocks for funded and unfunded when we make these changes live.

**Comment by ahmet-shamiev** [comment]
ok

**Comment by bobsummerwill** [comment]
Please can you implement these changes now?

Maybe just clone https://etcgrants.softr.app/projects-details-en first and make the changes for my review?  Thanks!

**Comment by bobsummerwill** [comment]
Bob Summerwill, [7/13/23 10:26 A.M.]
@Ahmet_Sh Are you around?   We have an urgent deadline.   If you can do this last issue today that would be hugely appreciated.

Bob Summerwill, [7/13/23 10:27 A.M.]
And for now let's OMIT the review comments fields from the views which are being updated, so that the Funded/Unfunded is the only thing which is currently being revealed to the public here.   I need to work through all the comment fields and clean them up before that detail is public.   Thanks!

**Comment by bobsummerwill** [comment]
This issue got a bit big and was largely resolved, so I will close it and make new smaller issues for anything outstanding I spot.  Thanks!
