### ISSUE TITLE
Please add Funding field to all of the project details views

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#321]
The Funding field for projects was originally only visible within the Review workflow, but can be made entirely public soon.

That will entail adding it to each of the various project details views:

- project-details-en
- project-details-zh
- project-details-translation-en
- project-details-translations-cn
- project-details-review-en
- project-details-review-cn

**Comment by bobsummerwill** [comment]
At this point it will be possible to drop these views:

https://etcgrants.softr.app/funded-project-details-en
https://etcgrants.softr.app/funded-project-details-zh

And just use:

https://etcgrants.softr.app/project-details-en
https://etcgrants.softr.app/project-details-zh

**Comment by bobsummerwill** [comment]
Please proceed with this now, @ahmet-shamiev.  Thanks!

**Comment by ahmet-shamiev** [comment]
Hi, Bob. Completed. However it worth to ask where you'd think we need to place this field. Currently the Funding Status field os located under One Line Pitch field, basically at the top of the details page.

**Comment by bobsummerwill** [comment]
That location is fine, thank you.
