### ISSUE TITLE
URGENT#2 - Fix inconsistency of Chinese views

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#322]
Please can you switch these two views to use zh, not cn, for consistency.   Thanks!

- project-details-translations-cn
- project-details-review-cn

And obviously the references need fixing anywhere which uses these too.

**Comment by bobsummerwill** [comment]
Fix at will.

**Comment by bobsummerwill** [comment]
Sooner better than later on this one, actually, because it will invalidate existing links, so we should get those resolved before publishing them widely.

**Comment by ahmet-shamiev** [comment]
Completed. Links are updated.

**Comment by bobsummerwill** [comment]
Confirmed.  Thanks!
