### ISSUE TITLE
Funded Projects view is missing the description column under the folds

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#324]
Please can you add Project Description as the third column under the folds for both the English and Chinese sections of the Funded view, so that these three views all match:

- https://etcgrants.softr.app/projects-list-funded
- https://etcgrants.softr.app/projects-list-en
- https://etcgrants.softr.app/projects-list-zh

Right now the Funded view is missing that third column.  Thanks!

**Comment by ahmet-shamiev** [comment]
Completed.

**Comment by bobsummerwill** [comment]
Thanks - confirmed
