### ISSUE TITLE
URGENT#3 - Times Financial was done the wrong way around

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#328]
The applicant for TIMES FINANCIAL did an English language application onto the Chinese form.

Please could you carefully manually switch the fields around to be the right way around?

We have now applied translations for all of the funded projects, and those are showing appropriately as expected in projects-list-en and projects-list-zh.  Hurrah!

**Comment by ahmet-shamiev** [comment]
Hi Bob, I've switched the texts.

**Comment by bobsummerwill** [comment]
Great- thank you!
