### ISSUE TITLE
URGENT#1 - Two new "funded" views, please.

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#330]
The current "projects-list-funded" does not include any translations.

It shows a section for English applications and a section for Chinese applications, but they are strictly segmented by original language form.  We could switch that to match "projects-list-en" and "projects-list-zh" together on a single page, but I think it would be better to ...

Create two new views:
    "projects-list-funded-en" and "projects-list-funded-zh"
    
Which act just like "projects-list-en" and "projects-list-zh" apart from that they filter to only show the funded projects.  Both would show the combined list of original language and translated versions.

When these new views are working and approved by me, we would delete "projects-list-funded" because we would not need it anymore.  It was only necessary while we were missing the translations.

We would then link these new views from the website when we reveal the results of the funding.  Thanks!

**Comment by ahmet-shamiev** [comment]
Hi Bob, 

I updated the initial ""projects-list-funded"" view and now both language versions include translations. As wells as created mentioned pages of only funded projects. Please check all three links.

**Comment by bobsummerwill** [comment]
https://etcgrants.softr.app/projects-list-funded-en is good.

https://etcgrants.softr.app/projects-list-funded-zh is missing.

https://etcgrants.softr.app/projects-list-funded is good, but we can delete this when the Chinese link above works.

Thanks!

**Comment by ahmet-shamiev** [comment]
Apologies, made some mistyping in link url, the https://etcgrants.softr.app/projects-list-funded-zh works now.

**Comment by bobsummerwill** [comment]
Great - thanks, confirmed.

Please can you delete https://etcgrants.softr.app/projects-list-funded now, and we can close this issue.

**Comment by ahmet-shamiev** [comment]
Done.
