### ISSUE TITLE
URGENT - Please can you change all the list views to be in alphabetical order?

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#337]
Please can you change all the list views to be in alphabetical order?

They are all in ID order now, so are pretty random looking.

If you are able to do this tomorrow morning your time (ahead of a Twitter Spaces at 10 Eastern, which I think is 5pm your time?) then please do so - it would be very helpful.

**Comment by ahmet-shamiev** [comment]
Hi Bob, hope not too late. I've sorted all list views by project name A-Z.

**Comment by bobsummerwill** [comment]
That is great, thank you!

Not too late. We just ordered them in our blog posts manually, but not the website matches too.

Best wishes!
