### ISSUE TITLE
Please replace funded-project-details-en and funded-project-details-zh

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#348]
Now that we are making Funded status visible in project-details-en and project-details-zh, there is no need for the specific "funded" project details views.

Please could you delete these views and just link to project-details-en and project-details-zh from projects-list-funded-en and projects-list-funded-zh?

Thanks!

**Comment by ahmet-shamiev** [comment]
Hi Bob, yes, I can hide these views. Right now, project details views are linked with projects-lists-en and zh. Is it what you were asking for?

**Comment by bobsummerwill** [comment]
Yes.  We don't need specific "funded details" view anymore.

The "project details" can be used from both the full lists and the funded lists.

Please could you make that simplification?  Thanks!

**Comment by ahmet-shamiev** [comment]
Got it. Completed.

**Comment by bobsummerwill** [comment]
Thanks!
