### ISSUE TITLE
Finalize OG tags and other metadata

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#35]
Andrew to finalize what this should be and then Bob can make the changes (or Andrew himself!)

**Comment by andrewgdick** [comment]
<meta property="og:image" content="../images/heroBgMobile.svg"/>
<meta property="og:title" content="ETC Grants DAO"/>
<meta property="og:description" content="A non-profit decentralized autonomous organization providing grants to ETC developers, aiming to promote the ecological construction and long-term development of Ethereum Classic. "/>
<meta property="og:site_name" content="ETC Grants DAO">
<meta property="og:url" content="https://etcgrantsdao.io/">
<meta property="og:type" content="website">

I'd like to change the image file. I have used the BG image as a placeholder.

**Comment by andrewgdick** [comment]
I have added the code to the index.html
