### ISSUE TITLE
URGENT (4/4) - Make proper use of the Vue framework

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#36]
We really don't want to have raw HTML to maintain.
There must be some controls within the Vue framework which we can use to compose the structure of the content in a way which looks simpler and is more maintainable.

Maybe there is some control which just uses MD files and we can use those as the means of composition?   Just end up with two MD files - one per language?

Or maybe just parts of the main page are done with MDs?

Or maybe we stick with the current JSON strings, but just find a better way of using the components.

The goal is for it is be possible to update the structure in simple ways (ie. adding removing sections or paragraphs) without having to do large cut and pastes

**Comment by SPTechnology** [comment]
Tying this into my question in issue 31 - can we assume that the styling will be the same across multiple languages? Using a single reusable component and telling the component to use different JSON strings depending on the selected language is probably the most reusable way to do this. 

That way we only have to add new JSON if you decide to support a third or fourth language (as well as a selector for the language of course).

**Comment by bobsummerwill** [comment]
Generally the content structure will be the same, I think, yes, and so the translation strings are OK, I think.

The nesting I did with the JSON gives a good enough indication of the structure than the translator can see how the strings are being used, so there is no the issue you sometimes have of having a raft of hundreds of strings in a linear structure and you don't really see how they are used.

But on the other hand, if we can get a lot of structure coming from MD files then I think the redundancy is OK for the benefit of being able to see text closer to the final output.    That also allows for the possibility of slight tweaks for particular languages (extra paragraphs, more context or whatever where you are actually i18n vs just translating.

For now I think we can assume common structure, though.

**Comment by bobsummerwill** [comment]
We are getting there, I think.
Getting much better.

**Comment by bobsummerwill** [comment]
@SPTechnology Gabriel is starting work with us tomorrow.

He is a Vue.js expert and I'm reassigning these structural issues to him.

**Comment by bobsummerwill** [comment]
Superceded by https://github.com/ETCGrantsDAO/etc-grants-dao-website/issues/96.
