### ISSUE TITLE
URGENT (3/4) - Find some means of doing string substitutions for the hyperlinks within text

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#37]
We need some means of embedding string substitutions within the translations, for including hyperlinks without having to split translation strings so finely grained.

Example:

"body": "This is the body of the text, but including a {{hyperlink-airtable}}",

"hyperlink-airtable.text": "Link to airtable",
"hyperlink-airtable.link": "https://airtable.com",

So the text can be totally different by language (and may or may not include a link even), and also the link text is still localized.

Something like this anyway.

**Comment by SPTechnology** [comment]
On it!

**Comment by bobsummerwill** [comment]
See some experiments here:
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/77

**Comment by bobsummerwill** [comment]
Are you going to be able to look at this over the weekend, @SPTechnology?  Thanks!

**Comment by bobsummerwill** [comment]
@SPTechnology Gabriel is starting work with us tomorrow.

He is a Vue.js expert and I'm reassigning these structural issues to him.

**Comment by bobsummerwill** [comment]
Using https://github.com/ETCGrantsDAO/etc-grants-dao-website/issues/95 to track this.
