### ISSUE TITLE
Page Title - ETC Grants DAO - no link

### ISSUE THREAD

**Issue by andrewgdick** [ETCGrantsDAO/etc-grants-dao-website#56]
Please add index.html link to "ETC Grants DAO" Logo/Title

**Comment by bobsummerwill** [comment]
Sorry - please could you make this more explicit?
That clicking on the image returns the page to its default state?
Same as already happens for Content?

**Comment by bobsummerwill** [comment]
Fixed in https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/63
