### ISSUE TITLE
URGENT - Mobile nav is broken.  Hamburger does nothing, and then all the mobile links need testing.

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#64]
None of the links in the desktop nav work.
The anchors must have been removed/broken during the "Dev" reorg.

The language toggle is missing on both desktop and mobile.

Clicking on the hamburger on mobile does not bring up the nav.

**Comment by SPTechnology** [comment]
When I separated component I forget to import the other code... I am working on it now

**Comment by SPTechnology** [comment]
I tested again and all nav links are working fine in desktop.

Toggle and hamburger is also working fine

**Comment by bobsummerwill** [comment]
Against etcgrants.org live?   Or against your local build?

I will sync some older commits and try to work out where it got broken.

**Comment by SPTechnology** [comment]
Just tested the live site and mobile NAV seems to work for the main headers 🤔

**Comment by SPTechnology** [comment]
Live build is definitely wonky though, yeah.

**Comment by bobsummerwill** [comment]
It got broken by "Dev' changes, same as the LocaleToggle did.

I branched and tested the changes before, on and after that commit:
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/53

What is your local build?   Did you guys refresh your repos after the commits from that PR onwards?

You are very out of sync:
https://github.com/SPTechnology/etc-grants-dao-website/tree/dev
"This branch is [5 commits ahead](https://github.com/SPTechnology/etc-grants-dao-website/compare/ETCGrantsDAO:etc-grants-dao-website:main...dev), [7 commits behind](https://github.com/SPTechnology/etc-grants-dao-website/compare/dev...ETCGrantsDAO:etc-grants-dao-website:main) ETCGrantsDAO:main."

**Comment by bobsummerwill** [comment]
Better to ditch your "dev" branch, sync your main to the upstream and make a new branch.

Also better to do branches per change, not a long-living "dev", because we have multiple people working here, so small atomic changes are the way to go.  The "big diffs" are mainly done, so we should not be stepping on each other too much, but we need to stay close, so small branches from the head are best.

**Comment by SPTechnology** [comment]
I made another pull request with a new branch... Some of links was working in dev as well but some was missing. Now all the links in desktops are working

**Comment by bobsummerwill** [comment]
Both pull requests you created had significant merge conflicts, so I closed them.
I grabbed your LocaleSwitcher fix and merged that.

But the nav links are still broken on desktop and mobile.

Please can you either refresh your branches with everything, or make new ones?
Looks from your prior diffs like the link fixes were all pretty similar and should merge nicely when they are made against the latest tip?  Thanks!

**Comment by bobsummerwill** [comment]
We need PRs with ONLY those link changes.

**Comment by bobsummerwill** [comment]
I grabbed the desktop fixes too and merged them.

Mobile still broken and the hamburger button does not work to even see them.

**Comment by bobsummerwill** [comment]
Are you going to be able to look at this over the weekend, @SPTechnology?  Thanks!

**Comment by SPTechnology** [comment]
I createda new fork and fixed the code. Now I don't think there will be any issue

**Comment by bobsummerwill** [comment]
All fixed, confirmed.   Thank you!
