### ISSUE TITLE
Create images for categories table and for the timetable table (need both English and Chinese versions)

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#79]
It needs some more padding, and, I think, some lines between the cells.

**Comment by SPTechnology** [comment]
I made a push fixing the issue, can you please check

**Comment by bobsummerwill** [comment]
Yes, that looks better, thanks.

Is it possible, please, to expand the table to the full switch of the main column?
Right now it is very narrow (probably specifically designed so in its original form showing the different projects).
I repurposed it but there is a lot of wrapping because it is so narrow.

The first column wraps every character in Chinese.

**Comment by bobsummerwill** [comment]
I think we might be better just having a static image for this.

CC @andrewgdick.

**Comment by bobsummerwill** [comment]
I replaced it with a static image, to see how it looked, and it is way better.
So we just need to get something which looks good, in both English and Chinese versions.
Preferably matching the fonts here.

**Comment by bobsummerwill** [comment]
Actually - let me put this on your plate, Andrew!

**Comment by bobsummerwill** [comment]
Fixed today
