### ISSUE TITLE
URGENT - Knock-on issue from the fix for anchors

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#91]
It looks like the change which made the sub-headings go the right place has broken the headings.

"How to Apply" and "Resources" go the right place, but the other headings do not.

**Comment by gd8097019** [comment]
Hi I don't understand or see where is the issue, can you provide image or some example ?

**Comment by gd8097019** [comment]
Hi, I can't understand where exatcly is the problem, can you send some screenshots?

**Comment by bobsummerwill** [comment]
So Overview goes too low down.
How to Apply is correct.
ETC Grants Process goes too low down.
Resources goes too low down.

Pretty much every subheading is broken again now (presumably because of the padding fixes which were just merged.

At least a few of the sub-heading have a wrong anchor and don't work at all.

**Comment by bobsummerwill** [comment]
Fix in progress by @gd8097019 in this PR:
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/124

**Comment by bobsummerwill** [comment]
It is resolved - thanks!
