### ISSUE TITLE
Make proper use of Vue.js

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#96]
The current website is unmaintainable because everything is bound together too tightly.

We need to have clear separation between:

1. Content, currently in the form of JSON text strings, but ideally should be in MD files later on.
2. Structure, currently in the form of the various .vue files
3. Presentation, mainly in CSS files, but some in the .vue files too

We need myself and members of the ETC Cooperative and Bitmain comms teams to be able to update content without assistance.  That is not currently possible except for very trivial changes because everything is so tightly bound and hard-coded.  Even something as simple as adding/removing paragraphs touches the vue files and requires cut-and-paste HTML.

We need to be able to make style changes without touching many files.   As much as humanly possible that should all live in the CSS files or tailwind files.   Not in the .vue files or within their hardcoded HTML chunks.

Simple structural changes (adding/removing/reordering new sections) should not be difficult and require touches in many places.

There are different elements to solving this over-arching problem and it might be easily to address this one step at a time, with multiple refactorings.

**Comment by gd8097019** [comment]
Hi, I think we completed this issue by dividing small issues.

Right now project uses `.md` file
Sections are generated from `sections.json` file

I also checked for hard-coded css but there is not exist any hardcoded css

I think this issue can be closed right now. 

Thanks.

**Comment by bobsummerwill** [comment]
OK - if you think that what we have is "good enough", then sure.
